### ISSUE TITLE
Requesting access

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/neurotune#13]
Hi @apdavison : would you be able to add me to this repo when you have a minute please? We're updating the code here so it'll make it easier if I could push minor changes directly instead of waiting for Padraig to merge all my PRs.

Also, looks like @pgleeson has write access here, but not the required access to add/remove folks to the repo. Would it be OK to please 
 bump up their access too so we don't have to trouble you for this again :)?

Thanks very much,

**Comment by apdavison** [comment]
hi @sanjayankur31 I've bumped the neurotune-developers group (which both you and @pgleeson are members of) up to admin status

**Comment by sanjayankur31** [comment]
Thanks very much :)

**Comment by pgleeson** [comment]
Thanks @apdavison!
